# Generated by Django 4.1.3 on 2023-01-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=60)),
                ('package', models.CharField(max_length=20)),
            ],
        ),
    ]
