# Generated by Django 4.1.4 on 2023-01-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genexpAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
